# Generated by Django 5.2.11 on 2026-03-07 01:25

import Parts.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('mpn', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Manufacturer Part Number')),
                ('image_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('weight_g', models.PositiveIntegerField(blank=True, null=True, verbose_name='Weight (g)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate_provider', models.CharField(blank=True, max_length=50)),
                ('affiliate_url', models.URLField(blank=True)),
                ('asin', models.CharField(blank=True, max_length=10)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Parts.component')),
                ('cells', models.PositiveIntegerField(choices=[(3, '3S'), (4, '4S'), (6, '6S'), (8, '8S')])),
                ('capacity_mah', models.PositiveIntegerField()),
                ('discharge_rate_c', models.CharField(blank=True, help_text="e.g. '120C'", max_length=50)),
                ('connector', models.CharField(blank=True, help_text="e.g. 'XT60', 'XT30'", max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('Parts.component',),
        ),
        migrations.CreateModel(
            name='ESC',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Parts.component')),
                ('continuous_current_a', models.PositiveIntegerField(help_text='Continuous amp rating')),
                ('burst_current_a', models.PositiveIntegerField(blank=True, null=True)),
                ('voltage_min', models.PositiveIntegerField(default=3, help_text='Min cells, e.g. 3 for 3S')),
                ('voltage_max', models.PositiveIntegerField(default=6, help_text='Max cells, e.g. 6 for 6S')),
                ('protocol', models.CharField(blank=True, help_text="e.g. 'DShot600', 'PWM'", max_length=50)),
                ('mount_pattern', models.CharField(blank=True, help_text="e.g. '20x20_mm' or '30.5x30.5_mm'", max_length=50)),
                ('is_4in1', models.BooleanField(default=True, help_text='4-in-1 stack style?')),
            ],
            options={
                'abstract': False,
            },
            bases=('Parts.component',),
        ),
        migrations.CreateModel(
            name='FC',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Parts.component')),
                ('mount_pattern', models.CharField(blank=True, choices=[('20x20_mm', '20x20 mm'), ('30.5x30.5_mm', '30.5x30.5 mm')], max_length=50)),
                ('processor', models.CharField(blank=True, help_text="e.g. 'F722', 'H7'", max_length=50)),
                ('gyro', models.CharField(blank=True, help_text="e.g. 'ICM42688P'", max_length=50)),
                ('firmware', models.CharField(blank=True, help_text="e.g. 'Betaflight', 'INAV'", max_length=50)),
                ('cells_supported', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, help_text='[3,4,6] for voltage compat', size=None)),
                ('uart_count', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('Parts.component',),
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Parts.component')),
                ('frame_style', models.CharField(choices=[('freestyle', 'Freestyle'), ('racing', 'Racing'), ('cinewhoop', 'Cinewhoop'), ('long_range', 'Long Range'), ('cinelifter', 'Cinelifter'), ('toothpick', 'Toothpick')], default='freestyle', max_length=20)),
                ('wheelbase_mm', models.PositiveIntegerField(default=220, help_text='Diagonal motor-to-motor distance in mm')),
                ('prop_size_max_in', models.PositiveIntegerField(default=5, help_text='Max recommended prop diameter (inches)')),
                ('fc_mounting_pattern', models.CharField(blank=True, help_text="e.g. '20x20_mm', '30.5x30.5_mm'", max_length=50)),
                ('esc_mounting_pattern', models.CharField(blank=True, max_length=50)),
                ('motor_mounting', Parts.models.ChoiceArrayField(base_field=models.CharField(choices=[('16x16_mm', '16x16 mm'), ('16x19_mm', '16x19 mm'), ('12x12_mm', '12x12 mm'), ('9_mm', '9 mm')], max_length=20), blank=True, default=list, help_text="Supported motor mounting patterns, e.g. ['16x16_mm', '19x19_mm']", size=None)),
                ('stack_height_mm', models.PositiveIntegerField(blank=True, help_text='Max stack height clearance', null=True)),
                ('dry_weight_g', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dry Weight (g)')),
            ],
            options={
                'abstract': False,
            },
            bases=('Parts.component',),
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Parts.component')),
                ('kv_rating', models.PositiveIntegerField(help_text='RPM per volt')),
                ('stator_size', models.CharField(blank=True, help_text="e.g. '2207', '2306'", max_length=50)),
                ('mount_pattern', models.CharField(blank=True, help_text="e.g. '16x16_mm' – matches Frame.motor_mounting", max_length=20)),
                ('max_prop_size_in', models.PositiveIntegerField(blank=True, null=True)),
                ('max_voltage', models.DecimalField(blank=True, decimal_places=1, help_text='e.g. 6.0 for 6S max', max_digits=4, null=True)),
                ('test_thrust_g', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('Parts.component',),
        ),
        migrations.CreateModel(
            name='Propeller',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Parts.component')),
                ('size_in', models.DecimalField(decimal_places=2, help_text='e.g. 5.1', max_digits=4)),
                ('pitch_in', models.DecimalField(decimal_places=2, help_text='e.g. 4.3', max_digits=4)),
                ('blades', models.PositiveIntegerField(default=3)),
                ('material', models.CharField(blank=True, help_text="e.g. 'Polycarbonate'", max_length=50)),
                ('weight_g_per_prop', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('Parts.component',),
        ),
    ]
