# Generated by Django 5.2.11 on 2026-03-06 22:38

import Parts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Parts.component')),
                ('cells', models.PositiveIntegerField(choices=[(3, '3S'), (4, '4S'), (6, '6S'), (8, '8S')])),
                ('capacity_mah', models.PositiveIntegerField()),
                ('discharge_rate', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('Parts.component',),
        ),
        migrations.CreateModel(
            name='ESC',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Parts.component')),
                ('continuous_current', models.IntegerField()),
                ('burst_current', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('Parts.component',),
        ),
        migrations.CreateModel(
            name='FC',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Parts.component')),
                ('mounting', models.PositiveIntegerField(choices=[(16, '16x16 mm'), (20, '20x20 mm'), (25.5, '25.5x25.5 mm'), (30.5, '30.5x30.5 mm')])),
                ('cells', models.PositiveIntegerField(choices=[(3, '3S'), (4, '4S'), (6, '6S'), (8, '8S')])),
                ('weight_g', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('Parts.component',),
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Parts.component')),
                ('frame_style', models.CharField(choices=[('freestyle', 'Freestyle'), ('racing', 'Racing'), ('cinewhoop', 'Cinewhoop'), ('long_range', 'Long Range'), ('cinelifter', 'Cinelifter'), ('toothpick', 'Toothpick')], default='freestyle', max_length=20)),
                ('motor_mounting', Parts.models.ChoiceArrayField(base_field=models.CharField(choices=[('16x16_mm', '16x16 mm'), ('16x19_mm', '16x19 mm'), ('12x12_mm', '12x12 mm'), ('9_mm', '9 mm')], max_length=20), blank=True, default=list, size=None)),
                ('Motor_Count', models.IntegerField(default=4)),
                ('Wheelbase', models.IntegerField(default=6)),
                ('Prop_Size', models.IntegerField(default=6)),
                ('dry_weight_g', models.IntegerField(db_comment='Frame weight without electronics, in grams', help_text='in grams (g)', verbose_name='Dry Weight')),
            ],
            options={
                'abstract': False,
            },
            bases=('Parts.component',),
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Parts.component')),
                ('kv_rating', models.IntegerField()),
                ('stator_size', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('Parts.component',),
        ),
    ]
