# Generated by Django 5.2.11 on 2026-02-25 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Parts.component')),
                ('frame_style', models.CharField(choices=[('freestyle', 'Freestyle'), ('racing', 'Racing'), ('cinewhoop', 'Cinewhoop'), ('long_range', 'Long Range'), ('cinelifter', 'Cinelifter'), ('toothpick', 'Toothpick')], default='freestyle', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('Parts.component',),
        ),
    ]
