# Generated by Django 5.2.11 on 2026-03-07 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
