# Generated by Django 5.2.11 on 2026-03-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parts', '0002_alter_component_image_url'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='component',
            constraint=models.UniqueConstraint(fields=('brand', 'name'), name='unique_part'),
        ),
    ]
