# Generated by Django 5.2.11 on 2026-02-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parts', '0002_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='Prop_Size',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frame',
            name='Wheelbase',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frame',
            name='dry_weight_g',
            field=models.IntegerField(db_comment='Frame weight without electronics, in grams', default=10, help_text='in grams (g)', verbose_name='Dry Weight'),
            preserve_default=False,
        ),
    ]
