# Generated by Django 5.2.11 on 2026-02-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parts', '0003_frame_prop_size_frame_wheelbase_frame_dry_weight_g'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='Motor_Count',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='frame',
            name='Prop_Size',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='frame',
            name='Wheelbase',
            field=models.IntegerField(default=6),
        ),
    ]
