# Generated by Django 5.2.11 on 2026-03-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parts', '0003_component_unique_part'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='component',
            name='unique_part',
        ),
        migrations.AddConstraint(
            model_name='component',
            constraint=models.UniqueConstraint(condition=models.Q(('brand', ''), _negated=True), fields=('brand', 'name'), name='unique_part'),
        ),
    ]
