# Generated by Django 5.2.11 on 2026-02-25 21:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parts', '0004_frame_motor_count_alter_frame_prop_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='motor_mounting',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('16x16_mm', '16x16 mm'), ('16x19_mm', '16x19 mm'), ('12x12_mm', '12x12 mm'), ('9_mm', '9 mm')], default='16x16_mm', max_length=20), blank=True, default=list, size=None),
        ),
    ]
