# Generated by Django 5.2.11 on 2026-03-13 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parts', '0004_remove_component_unique_part_component_unique_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='Parts.component')),
            ],
            options={
                'verbose_name': 'Price Snapshot',
                'verbose_name_plural': 'Price Snapshots',
                'ordering': ['-captured_at'],
            },
        ),
    ]
