# Generated by Django 5.2.11 on 2026-03-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parts', '0005_component_current_price_pricesnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='component',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='component',
            name='image_url',
            field=models.URLField(blank=True, help_text='Direct link to the product image on the affiliate site', max_length=500, null=True, verbose_name='Affiliate Image URL'),
        ),
    ]
