# Generated by Django 5.2.11 on 2026-03-14 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parts', '0006_component_active_component_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['name'], 'verbose_name': 'Component', 'verbose_name_plural': 'Components'},
        ),
        migrations.AlterField(
            model_name='component',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
