# Generated by Django 5.2.11 on 2026-03-06 21:55

import Parts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parts', '0008_alter_frame_motor_mounting'),
    ]

    operations = [
        migrations.CreateModel(
            name='FC',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Parts.component')),
                ('mounting', models.PositiveIntegerField(choices=[(16, '16x16 mm'), (20, '20x20 mm'), (25.5, '25.5x25.5 mm'), (30.5, '30.5x30.5 mm')])),
                ('cells', models.PositiveIntegerField(choices=[(3, '3S'), (4, '4S'), (6, '6S'), (8, '8S')])),
                ('weight_g', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('Parts.component',),
        ),
        migrations.AlterField(
            model_name='battery',
            name='cells',
            field=models.PositiveIntegerField(choices=[(3, '3S'), (4, '4S'), (6, '6S'), (8, '8S')]),
        ),
        migrations.AlterField(
            model_name='frame',
            name='motor_mounting',
            field=Parts.models.ChoiceArrayField(base_field=models.CharField(choices=[('16x16_mm', '16x16 mm'), ('16x19_mm', '16x19 mm'), ('12x12_mm', '12x12 mm'), ('9_mm', '9 mm')], max_length=20), blank=True, default=list, size=None),
        ),
    ]
